<?php
$itemsCollection = $block->getBestSoldItems();
$image = 'product_page_image_small';
$_helper = $this->helper('Magento\Catalog\Helper\Output');

if (count($itemsCollection) > 0) : ?>
<div class="block-bestsellers">
    <div class="block-title">
        <h3><?php echo __('Best Sold Products'); ?></h3>
    </div>
    <div class="block-content">
        <ul>
        <?php foreach ($itemsCollection as $_product) : ?>
            <li>
                <div class="product" data-product-id="<?php echo $_product->getId(); ?>">
                    <?php // Product Image 
                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                    ?>
                    <div class="product-top-left">
                        <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo">
                            <?php echo $block->getImage($_product, $image)->toHtml(); ?>
                        </a>
                    </div>
                    <div class="product-top-right">
                        <div class="product details">
                            <div class="product-right-title">
                                <a class="product-item-link"
                                href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                    <?php /* @escapeNotVerified */ echo $_product->getName(); ?>
                                </a>
                            </div>
                            <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                            <div class="product-add-form product actions product-item-actions">
                                <div class="actions-primary product-options-bottom">
                                    <div class="box-tocart">
                                        <div class="actions">                                                                                                        
                                            <button onclick='location.href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>"'
                                                    title="<?php echo $block->escapeHtml(__('View details')); ?>"
                                                    class="action view primary greenBtn">
                                                <span><?php /* @escapeNotVerified */ echo __('View details') ?></span>
                                            </button>
                                            <?php if ($_product->getIsSalable()): ?>
                                                <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>                                
                            </div>
                        </div>
                    </div>
                </div>                
            </li>
        <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; 
