<?php $item = $block->getCurrentNews(); ?>
<meta property="og:url" content="<?php echo $block->getCurrentSeoLink(); ?>" />
<meta property="og:type" content="article" />
<meta property="og:title" content="<?php echo $item->getTitle(); ?>" />
<meta property="og:description" content="<?php echo strip_tags($item->getShortContent()); ?>" />
<meta property="og:image" content="<?php echo $item->getImageUrl() ?>" />
<meta property="article:published_time" content="<?php echo $item->getPublishAt() ?>" />
<meta property="article:author" content="<?php echo $item->getAuthor() ?>" />
<link rel="canonical" href="<?php echo $block->getCurrentSeoLink(); ?>" />
<!-- Twitter script -->
<script>window.twttr = (function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0],
    t = window.twttr || {};
  if (d.getElementById(id)) return t;
  js = d.createElement(s);
  js.id = id;
  js.src = "https://platform.twitter.com/widgets.js";
  fjs.parentNode.insertBefore(js, fjs);
  t._e = [];
  t.ready = function(f) {
    t._e.push(f);
  };
  return t;
}(document, "script", "twitter-wjs"));</script>
<!-- Google script -->
<script src="https://apis.google.com/js/platform.js" async defer></script>
